"""Curated study cards for the Glossary Learning feature.

Each entry mirrors one glossary term-box (templates/glossary/_*.html). term_title
must match the glossary <span class="term-title"> text exactly (entity-decoded,
whitespace-normalized) -- tests/test_glossary_learn_seed.py enforces this.

Adding a new glossary term? Add its term-box to the relevant templates/glossary/_*.html
partial, then add a matching entry here (section_id must be an existing LEVELS entry,
or a new one). See assets/glossary_learning.md for the full checklist.
"""

LEVELS = [
    ("market-fundamentals", "Market Fundamentals"),
    ("candlesticks", "Candlestick Anatomy"),
    ("technicals", "Technical Analysis"),
    ("fundamentals", "Company Valuation"),
    ("strategies", "Trading Strategies"),
    ("machine-learning", "AI & Risk Metrics"),
    ("earnings-vol", "Earnings Volatility"),
    ("dip-radar", "Dip Radar"),
    ("bubble-radar", "Bubble Radar"),
    ("forensic-screener", "Forensic Screener"),
    ("fx-drag", "FX Drag Analyzer"),
    ("performance-analytics", "Portfolio Tearsheet"),
    ("stress-tester", "Stress Tester"),
    ("etf-predictor", "ETF Predictor"),
    ("sovereign-debt-auction", "Sovereign Debt Auction"),
    ("accounts", "Built-in Accounts"),
    ("backup-recovery", "Backup & Recovery"),
    ("security-access", "Security & Access"),
    ("workflow-monitor", "Workflow Monitor"),
    ("notification-routing", "Notification Routing"),
    ("methodology", "System Methodology"),
]

CARDS = [
    # --- market-fundamentals ---
    {
        "term_key": "stocks-and-shares",
        "section_id": "market-fundamentals",
        "term_title": "Stocks & Shares — What You Actually Own",
        "question": "What does owning a share of a company actually give you?",
        "answer": "A proportional slice of ownership in the company, including a claim on its assets",
        "distractors": [
            "A guaranteed fixed interest payment from the company each year",
            "The right to demand a refund of your investment at any time",
            "A management role in how the company is run day-to-day",
        ],
    },
    {
        "term_key": "bonds-govt-corporate-iou",
        "section_id": "market-fundamentals",
        "term_title": "Bonds — Government and Corporate IOUs",
        "question": "Why do bond prices fall when interest rates rise?",
        "answer": "A bond's fixed coupon becomes less attractive compared to new bonds paying the higher prevailing rate",
        "distractors": [
            "Governments automatically reduce the face value of existing bonds when rates rise",
            "Rising rates increase the coupon paid on already-issued bonds, so buyers pay more upfront",
            "Bond maturities shorten automatically when interest rates increase",
        ],
    },
    {
        "term_key": "etfs-exchange-traded-funds",
        "section_id": "market-fundamentals",
        "term_title": "ETFs — Exchange-Traded Funds",
        "question": "What is the main advantage of a passive ETF over an actively managed fund?",
        "answer": "It tracks an index automatically, keeping fees far lower than most actively managed funds that fail to beat the index anyway",
        "distractors": [
            "It guarantees a fixed annual return regardless of market conditions",
            "It only holds a single company, reducing complexity",
            "It cannot be bought or sold during market hours, reducing volatility",
        ],
    },
    {
        "term_key": "market-capitalisation",
        "section_id": "market-fundamentals",
        "term_title": "Market Capitalisation (Market Cap)",
        "question": "How is a company's market capitalisation calculated?",
        "answer": "Share price multiplied by the total number of outstanding shares",
        "distractors": [
            "Total annual revenue minus total operating costs",
            "The book value of all the company's assets minus liabilities",
            "Share price multiplied by average daily trading volume",
        ],
    },
    {
        "term_key": "markets-page-region-tile-status",
        "section_id": "market-fundamentals",
        "term_title": "Markets Page — Region & Tile Status",
        "question": "What does a tile with a diagonal-stripe overlay on the Markets page indicate?",
        "answer": "The tile's market should be open but its price data hasn't refreshed as expected — worth a manual check",
        "distractors": [
            "The instrument has been permanently delisted",
            "The tile's region status is \"Some Open\"",
            "The price shown is from a currency-converted future contract",
        ],
    },
    {
        "term_key": "bull-bear-markets",
        "section_id": "market-fundamentals",
        "term_title": "Bull Markets & Bear Markets",
        "question": "Why does managing downside risk matter more than chasing returns in a bear market?",
        "answer": "A 50% decline requires a 100% subsequent gain just to break even",
        "distractors": [
            "Bear markets always last longer than bull markets",
            "Regulators require reduced position sizes during declines of 20% or more",
            "Bull markets are defined as periods with lower trading volume than bear markets",
        ],
    },
    {
        "term_key": "bid-ask-spread",
        "section_id": "market-fundamentals",
        "term_title": "Bid, Ask & Spread — The Hidden Cost of Every Trade",
        "question": "If you buy at the ask and immediately sell at the bid, what have you lost?",
        "answer": "The spread — the gap between the bid and ask price — before the stock even moves",
        "distractors": [
            "Nothing, since bid and ask are always identical for liquid stocks",
            "A regulatory transaction tax charged only on same-day trades",
            "The stock's average daily volatility",
        ],
    },
    {
        "term_key": "options-calls-puts",
        "section_id": "market-fundamentals",
        "term_title": "Options — Calls & Puts",
        "question": "What does buying a call option give you the right to do?",
        "answer": "Buy 100 shares at the strike price before expiry",
        "distractors": [
            "Sell 100 shares at the strike price before expiry",
            "Receive a guaranteed dividend from the underlying stock",
            "Vote on company matters in place of the shares themselves",
        ],
    },
    {
        "term_key": "dividends-dividend-yield",
        "section_id": "market-fundamentals",
        "term_title": "Dividends & Dividend Yield",
        "question": "Why can a rising dividend yield be a warning sign rather than good news?",
        "answer": "A rising yield often means the share price has fallen, which can signal the dividend is about to be cut",
        "distractors": [
            "A rising yield always means the company has just raised its dividend payment",
            "Dividend yield only rises when a company issues new shares",
            "A rising yield means the company has stopped paying corporate tax",
        ],
    },
    {
        "term_key": "stock-market-indices",
        "section_id": "market-fundamentals",
        "term_title": "Stock Market Indices — S&P 500, FTSE 100, and Others",
        "question": "Why does the S&P 500 move more from Apple, Microsoft, and NVIDIA than from smaller constituents?",
        "answer": "The index is weighted by market capitalisation, so larger companies have more influence",
        "distractors": [
            "Those three companies are excluded from the FTSE 100 for tax reasons",
            "The index only includes each company's most recent IPO price",
            "Smaller companies are removed from the index calculation during volatile periods",
        ],
    },
    {
        "term_key": "dynamic-view-follow-the-sun",
        "section_id": "market-fundamentals",
        "term_title": "Dynamic View — \"Follow the Sun\" Ordering",
        "question": "What does Dynamic View do on the Markets page?",
        "answer": "Reorders regional sections by which region's trading session is currently most relevant",
        "distractors": [
            "Permanently hides regions whose markets are closed",
            "Converts all prices into the user's home currency",
            "Randomises tile order to reduce visual bias toward any one region",
        ],
    },
    {
        "term_key": "session-driven-region-ordering",
        "section_id": "market-fundamentals",
        "term_title": "Session-Driven Region Ordering",
        "question": "When two regions are open at the same time, which one ranks first in Dynamic View?",
        "answer": "The region that opened most recently",
        "distractors": [
            "The region with the largest number of tracked tickers",
            "Whichever region is alphabetically first",
            "The region with the highest total market capitalisation",
        ],
    },
    {
        "term_key": "spot-futures-tiles",
        "section_id": "market-fundamentals",
        "term_title": "Spot/Futures Tiles",
        "question": "How does the Markets page show an index's cash and futures prices, compared to the Market Pulse widget?",
        "answer": "The Markets page shows both as two adjacent tiles, while Market Pulse shows only one, auto-swapping to futures when the cash market is closed",
        "distractors": [
            "Both surfaces always show only the futures price, never the cash price",
            "The Markets page hides the futures tile entirely until the cash market closes",
            "Market Pulse shows both tiles side by side, the same as the Markets page",
        ],
    },
    {
        "term_key": "what-is-a-portfolio",
        "section_id": "market-fundamentals",
        "term_title": "What Is a Portfolio?",
        "question": "Why does diversification often fail during a market crash, exactly when you need it most?",
        "answer": "During crashes, most asset correlations converge toward 1.0 as panic selling hits everything simultaneously",
        "distractors": [
            "Diversification rules are suspended by regulators during a declared market crash",
            "Crashes only affect single-asset portfolios, not diversified ones",
            "Correlation between assets always reaches exactly 0 during a crash",
        ],
    },

    # --- candlesticks ---
    {
        "term_key": "reading-a-candlestick-basics",
        "section_id": "candlesticks",
        "term_title": "Reading a Candlestick — The Basics",
        "question": "What does a long lower wick on a candlestick suggest?",
        "answer": "Sellers pushed the price down sharply intraday, but buyers forcefully rejected that low before the close",
        "distractors": [
            "The stock traded at the same price for the entire session",
            "The company announced a stock split during that session",
            "Trading volume was below the 20-day average for that session",
        ],
    },
    {
        "term_key": "hammer-bullish-rejection",
        "section_id": "candlesticks",
        "term_title": "🔨 The Hammer (Bullish Rejection)",
        "question": "What makes a Hammer pattern more significant?",
        "answer": "It appears after a multi-day downtrend, with above-average volume and next-day follow-through above its body",
        "distractors": [
            "It appears in the middle of a sideways, rangebound market with no trend",
            "It has a long upper wick and a small body near the bottom of its range",
            "It occurs on unusually low trading volume with no confirmation needed",
        ],
    },
    {
        "term_key": "bullish-engulfing",
        "section_id": "candlesticks",
        "term_title": "🐂 Bullish Engulfing",
        "question": "What defines a Bullish Engulfing pattern?",
        "answer": "Day 2's green body completely swallows Day 1's red body after opening lower",
        "distractors": [
            "Two consecutive candles of identical size and colour",
            "A single candle with a very long upper wick and small body",
            "Day 2 gaps up and closes without any wicks at all",
        ],
    },
    {
        "term_key": "morning-star-3-candle",
        "section_id": "candlesticks",
        "term_title": "🌅 Morning Star (3-Candle)",
        "question": "What is the sequence of the three candles in a Morning Star pattern?",
        "answer": "A large red body (panic), a small indecision candle like a Doji, then a large green body closing above Day 1's midpoint",
        "distractors": [
            "Three consecutive large green candles each closing at a new high",
            "A Doji, followed by two large red candles",
            "A large green candle followed by two small red candles of decreasing size",
        ],
    },
    {
        "term_key": "three-white-soldiers-3-candle",
        "section_id": "candlesticks",
        "term_title": "🪖 Three White Soldiers (3-Candle)",
        "question": "What distinguishes Three White Soldiers from a simple three-day rally?",
        "answer": "Each candle opens within the prior candle's body and closes near its session high, showing sustained buying rather than gap-driven moves",
        "distractors": [
            "Each candle must gap up significantly above the prior day's close",
            "The pattern requires declining volume across all three sessions",
            "Each candle must have a long lower wick",
        ],
    },
    {
        "term_key": "harami-cross",
        "section_id": "candlesticks",
        "term_title": "🌱 Bullish Harami Cross / 🕸️ Bearish Harami Cross (2-Candle)",
        "question": "What makes the Harami Cross variant stronger than a regular Harami?",
        "answer": "The second candle is a Doji, showing the prior trend was completely stalled with no net movement",
        "distractors": [
            "The second candle must be larger than the first candle's entire body",
            "It requires three additional candles of confirmation before it counts",
            "The pattern only occurs on weekly charts, never daily",
        ],
    },
    {
        "term_key": "piercing-line-2-candle",
        "section_id": "candlesticks",
        "term_title": "🗡️ Piercing Line (2-Candle)",
        "question": "What threshold must Day 2 close above for a Piercing Line pattern?",
        "answer": "The midpoint of Day 1's red candle body",
        "distractors": [
            "Day 1's opening price exactly",
            "The 200-day moving average",
            "Day 1's highest intraday wick",
        ],
    },

    # --- technicals ---
    {
        "term_key": "moving-averages",
        "section_id": "technicals",
        "term_title": "Moving Averages (5D, 10D, 21D, 50D, 200D)",
        "question": "What is a 'Golden Cross'?",
        "answer": "When the 50-day moving average crosses above the 200-day moving average",
        "distractors": [
            "When price crosses above the 21-day EMA for the first time",
            "When the 5-day MA crosses below the 10-day MA",
            "When RSI crosses above 70 while price is above the 200-day MA",
        ],
    },
    {
        "term_key": "change-period",
        "section_id": "technicals",
        "term_title": "Change Period (1D, 5D, 1M, 6M, YTD, 1Y)",
        "question": "What does the YTD Change Period compare the live price against?",
        "answer": "The last close of the previous calendar year",
        "distractors": [
            "The close exactly 5 trading sessions ago",
            "The all-time high price for that ticker",
            "The average price over the past 200 trading days",
        ],
    },
    {
        "term_key": "rsi-relative-strength-index",
        "section_id": "technicals",
        "term_title": "RSI (Relative Strength Index)",
        "question": "What does RSI Divergence signal when price makes a new high but RSI makes a lower high?",
        "answer": "The new price high was achieved on declining momentum — a warning the uptrend may be weakening",
        "distractors": [
            "The stock is guaranteed to reverse within the next trading session",
            "Trading volume has definitely increased on the new high",
            "The company is about to announce an earnings beat",
        ],
    },
    {
        "term_key": "atr-stop-loss",
        "section_id": "technicals",
        "term_title": "ATR Stop-Loss (Average True Range)",
        "question": "Why use ATR rather than a fixed percentage to set a stop-loss?",
        "answer": "ATR makes the stop adaptive to the stock's own typical volatility, rather than applying the same fixed percentage to every position",
        "distractors": [
            "ATR guarantees the stop-loss will never be triggered by normal price action",
            "ATR is only usable for stocks with beta above 1.5",
            "ATR removes the need to ever review a position once it's set",
        ],
    },
    {
        "term_key": "volume-profile-poc",
        "section_id": "technicals",
        "term_title": "Volume Profile & POC (Point of Control)",
        "question": "What is the Point of Control (POC) in a Volume Profile?",
        "answer": "The single price level with the highest accumulated trading volume over the period",
        "distractors": [
            "The current live trading price at this exact moment",
            "The average of the day's high and low prices",
            "The price level with the lowest trading volume, signalling weak interest",
        ],
    },
    {
        "term_key": "keltner-channel-z-score",
        "section_id": "technicals",
        "term_title": "Keltner Channel Z-Score",
        "question": "What does a Keltner Channel Z-Score of -2 mean?",
        "answer": "The current close is two ATRs below the 21-day EMA — a notable oversold pullback within the channel",
        "distractors": [
            "The stock has fallen exactly 2% below its opening price today",
            "RSI has been below 30 for two consecutive trading sessions",
            "The stock's beta relative to the market is -2.0",
        ],
    },
    {
        "term_key": "ml-quantile-price-bands",
        "section_id": "technicals",
        "term_title": "ML Quantile Price Bands (Q10 / Q90)",
        "question": "What does the Q90 band represent?",
        "answer": "In 90% of comparable historical situations, the stock reached or exceeded this price within the next 10 trading days — a data-driven optimistic target",
        "distractors": [
            "A guaranteed price ceiling the stock cannot exceed",
            "The stock's price exactly 90 trading days from today",
            "The 90th percentile of the stock's historical trading volume",
        ],
    },

    # --- fundamentals ---
    {
        "term_key": "what-is-fundamental-valuation",
        "section_id": "fundamentals",
        "term_title": "What Fundamental Valuation Means",
        "question": "How does fundamental analysis differ from technical analysis?",
        "answer": "Fundamental analysis asks what a company is actually worth based on financial performance, rather than looking at price charts and momentum",
        "distractors": [
            "Fundamental analysis only applies to bonds, never to individual stocks",
            "Fundamental analysis relies exclusively on candlestick patterns",
            "Fundamental analysis and technical analysis always produce identical buy/sell signals",
        ],
    },
    {
        "term_key": "peter-lynch-peg-ratio",
        "section_id": "fundamentals",
        "term_title": "Peter Lynch Fair Value — PEG Ratio",
        "question": "What does a PEG ratio of 1.0 represent under Peter Lynch's framework?",
        "answer": "\"Fair value\" — you are paying exactly in line with the company's earnings growth rate",
        "distractors": [
            "The stock is definitely overvalued regardless of growth",
            "The company has zero earnings growth",
            "The P/E ratio exceeds 30",
        ],
    },
    {
        "term_key": "financial-safety-debt-liquidity",
        "section_id": "fundamentals",
        "term_title": "Financial Safety — Debt & Liquidity",
        "question": "What does a Current Ratio below 1.0 indicate?",
        "answer": "The company cannot cover its near-term obligations with its near-term resources",
        "distractors": [
            "The company has no debt on its balance sheet",
            "The company's dividend yield exceeds its P/E ratio",
            "The company is guaranteed to file for bankruptcy within a year",
        ],
    },
    {
        "term_key": "quality-grade",
        "section_id": "fundamentals",
        "term_title": "Quality Grade (A–D)",
        "question": "What combination of factors earns a stock an 'A' Quality Grade?",
        "answer": "High ROE (>15%), low debt (<50% D/E), and a reasonable valuation (P/E <25 or PEG <1.5)",
        "distractors": [
            "The highest dividend yield in its sector",
            "The largest market capitalisation in its index",
            "Zero analyst coverage, indicating an under-the-radar opportunity",
        ],
    },
    {
        "term_key": "watchlist-report-screen-tags",
        "section_id": "fundamentals",
        "term_title": "Watchlist Report-Screen Tags",
        "question": "What does the 'Quality on Sale' tag indicate?",
        "answer": "The stock is within 15% of its 52-week low despite having solid fundamentals",
        "distractors": [
            "The stock has just cut its dividend payment",
            "The stock is trading at an all-time high with strong momentum",
            "The stock has failed the Beneish M-Score manipulation check",
        ],
    },

    # --- strategies ---
    {
        "term_key": "macd-reversal",
        "section_id": "strategies",
        "term_title": "⚡ MACD Reversal",
        "question": "What does it mean when the MACD line crosses above the Signal line?",
        "answer": "Short-term momentum is turning upward — the pace of a recent decline has slowed",
        "distractors": [
            "The stock has definitively bottomed and will not fall further",
            "Trading volume has tripled compared to the 20-day average",
            "The company has just reported positive earnings",
        ],
    },
    {
        "term_key": "vcp-breakout",
        "section_id": "strategies",
        "term_title": "🔥 VCP Breakout (Volatility Contraction Pattern)",
        "question": "What does the 'coiling' price action in a VCP represent?",
        "answer": "Weak holders being shaken out on shrinking dips while institutional buyers quietly absorb supply",
        "distractors": [
            "A company preparing to announce a stock buyback",
            "Retail investors panic-selling ahead of an earnings report",
            "Random noise with no informational content",
        ],
    },
    {
        "term_key": "bull-trap-dead-cat-bounce",
        "section_id": "strategies",
        "term_title": "🎭 Bull Trap / Dead Cat Bounce",
        "question": "What is the key volume tell that distinguishes a Bull Trap from a genuine recovery?",
        "answer": "A bull trap's bounce occurs on low volume, driven by short-covering rather than new committed buyers",
        "distractors": [
            "A bull trap always occurs on higher volume than the original decline",
            "Bull traps only happen in stocks with negative beta",
            "The price must close above the 200-day moving average to qualify",
        ],
    },
    {
        "term_key": "bear-trap-false-breakdown",
        "section_id": "strategies",
        "term_title": "🪤 Bear Trap / False Breakdown",
        "question": "What signals a Bear Trap rather than a genuine breakdown below support?",
        "answer": "The breakdown occurs on relatively low volume, and price closes back above the broken support level the same day",
        "distractors": [
            "The stock gaps down more than 10% on the breakdown day",
            "Short interest falls to zero immediately after the breakdown",
            "The breakdown is confirmed by RSI rising above 70",
        ],
    },
    {
        "term_key": "capitulation-final-flush",
        "section_id": "strategies",
        "term_title": "💥 Capitulation (The Final Flush)",
        "question": "Why is capitulation often bullish in its aftermath?",
        "answer": "Forced sellers have been flushed out, leaving mostly long-term holders and new buyers, so even modest demand can cause a sharp bounce",
        "distractors": [
            "Capitulation guarantees the stock will return to its prior all-time high within a week",
            "Capitulation only happens when a company reports a profit warning",
            "Trading is automatically halted for the rest of the session",
        ],
    },
    {
        "term_key": "wyckoff-accumulation-phase",
        "section_id": "strategies",
        "term_title": "🏗️ Wyckoff Accumulation Phase",
        "question": "Why does Smart Money accumulate shares slowly during the Wyckoff Accumulation Phase?",
        "answer": "Large institutions can't buy millions of shares without moving the price significantly, so they buy slowly to avoid revealing their hand",
        "distractors": [
            "Regulations require institutional purchases to be spread over at least six months",
            "Slow accumulation avoids capital gains tax on the eventual sale",
            "It allows the company to issue new shares at a discount",
        ],
    },
    {
        "term_key": "trap-phase-history-accuracy",
        "section_id": "strategies",
        "term_title": "📊 Trap Phase History & Prediction Accuracy",
        "question": "Why does the system require at least 5 resolved predictions per phase before showing an accuracy percentage?",
        "answer": "To avoid statistically meaningless figures from very small sample sizes",
        "distractors": [
            "Because regulations require a minimum sample size for financial claims",
            "Because fewer than 5 predictions would take too long to compute",
            "Because the Trap Monitor only scans 5 tickers per day",
        ],
    },
    {
        "term_key": "market-leader",
        "section_id": "strategies",
        "term_title": "👑 Market Leader",
        "question": "What does a positive Relative Strength (RS) reading indicate about a stock?",
        "answer": "The stock is performing better than the S&P 500 benchmark over the defined period",
        "distractors": [
            "The stock has the largest market capitalisation in its sector",
            "The stock pays the highest dividend yield among its peers",
            "The stock's beta is exactly 1.0",
        ],
    },

    # --- machine-learning ---
    {
        "term_key": "ml-confidence-score",
        "section_id": "machine-learning",
        "term_title": "ML Confidence Score",
        "question": "Why does the system use a Soft-Voting Ensemble of XGBoost and Random Forest rather than a single model?",
        "answer": "The two models have different strengths — XGBoost learns non-linear interactions well, Random Forest avoids overfitting to recent noise — so averaging their estimates is more robust",
        "distractors": [
            "Soft-voting always produces a higher score than either model alone",
            "XGBoost cannot process technical indicators, only fundamental data",
            "Random Forest is used only as a fallback when XGBoost fails to run",
        ],
    },
    {
        "term_key": "value-at-risk-95",
        "section_id": "machine-learning",
        "term_title": "Value at Risk — 1-day, 95% (Historical Simulation)",
        "question": "What does a 1-day 95% VaR of 12% mean for a position?",
        "answer": "There is a 95% probability the position will not lose more than 12% in a single trading day",
        "distractors": [
            "The position is guaranteed to lose exactly 12% at some point",
            "The position has a 95% chance of gaining 12% or more the next day",
            "95% of the position's value is held in cash reserves",
        ],
    },
    {
        "term_key": "conditional-var-cvar",
        "section_id": "machine-learning",
        "term_title": "Conditional VaR (CVaR) — Expected Shortfall",
        "question": "What does CVaR add beyond what VaR already tells you?",
        "answer": "The average severity of losses on the days that exceed the VaR threshold, not just the threshold itself",
        "distractors": [
            "CVaR always equals exactly half of the VaR figure",
            "CVaR replaces the need to calculate VaR at all",
            "CVaR measures only gains, never losses",
        ],
    },
    {
        "term_key": "vader-sentiment-score",
        "section_id": "machine-learning",
        "term_title": "VADER Sentiment Score",
        "question": "What is a key limitation of VADER sentiment scoring?",
        "answer": "It is purely lexical and doesn't deeply understand context — e.g. 'avoided a crash' scores negatively because of the word 'crash'",
        "distractors": [
            "It requires a live internet connection to an external API to function",
            "It cannot process any text longer than a single sentence",
            "It only works on non-English news articles",
        ],
    },
    {
        "term_key": "turbulence-index-volatility-regimes",
        "section_id": "machine-learning",
        "term_title": "Turbulence Index & Volatility Regimes",
        "question": "Why does the Turbulence Index use EWMA rather than a simple moving average?",
        "answer": "EWMA gives more weight to recent data, making it far more responsive to sudden volatility spikes",
        "distractors": [
            "EWMA is required by financial regulators for all volatility calculations",
            "EWMA removes the need to track FTSE data alongside SPY",
            "EWMA always produces a lower reading than a simple average",
        ],
    },
    {
        "term_key": "market-regime-price-hmm",
        "section_id": "machine-learning",
        "term_title": "Market Regime — Price HMM",
        "question": "What are the three hidden states the Price HMM classifies the market into?",
        "answer": "Bull, Chop, and Crash",
        "distractors": [
            "Risk-On, Late Cycle, and Stagflation",
            "Overbought, Neutral, and Oversold",
            "Accumulation, Markup, and Distribution",
        ],
    },
    {
        "term_key": "macro-regime-label",
        "section_id": "machine-learning",
        "term_title": "🌍 Macro Regime Label (Yield Curve Allocator)",
        "question": "What has an inverted yield curve historically preceded?",
        "answer": "Every US recession since the 1960s",
        "distractors": [
            "A guaranteed stock market rally within 3 months",
            "A mandatory Federal Reserve rate cut within 30 days",
            "A currency devaluation of the US dollar",
        ],
    },
    {
        "term_key": "portfolio-regime-alignment-score",
        "section_id": "machine-learning",
        "term_title": "Portfolio Regime Alignment Score",
        "question": "How is the Regime Alignment Score calculated?",
        "answer": "Cosine similarity between your current allocation weights and the ideal weights for the detected regime, scaled to 0-100",
        "distractors": [
            "The percentage of your portfolio held in cash",
            "The difference between your portfolio's beta and 1.0",
            "The number of asset classes currently held",
        ],
    },
    {
        "term_key": "isolation-forest-anomaly-score",
        "section_id": "machine-learning",
        "term_title": "Isolation Forest Anomaly Score",
        "question": "Why is the Isolation Forest described as 'unsupervised'?",
        "answer": "It needs no labelled data — it learns what 'normal' looks like for each ticker and flags deviations from that baseline",
        "distractors": [
            "It only runs once per year without any retraining",
            "It requires manual labelling of every anomaly before it can operate",
            "It only analyses a single data dimension per ticker",
        ],
    },
    {
        "term_key": "market-stress-score",
        "section_id": "machine-learning",
        "term_title": "Market Stress Score",
        "question": "How does the Market Stress Score differ from the Isolation Forest Anomaly Score?",
        "answer": "It measures whether the overall market environment is behaving strangely, using six macro features, rather than a single stock's behaviour",
        "distractors": [
            "It is calculated only once a year",
            "It replaces the need for the Price HMM regime classification",
            "It only applies to bond markets, never equities",
        ],
    },
    {
        "term_key": "monte-carlo-simulation",
        "section_id": "machine-learning",
        "term_title": "Monte Carlo Simulation",
        "question": "Why does the Monte Carlo engine simulate asset returns together using their real correlations, rather than independently?",
        "answer": "So that during a simulated equity crash, bonds behave as they historically have during equity crashes, not independently",
        "distractors": [
            "To guarantee every simulated path shows a positive return",
            "To reduce the number of simulations needed from 1,000 to 10",
            "Because correlated simulation runs faster than independent simulation",
        ],
    },
    {
        "term_key": "drift-assumption",
        "section_id": "machine-learning",
        "term_title": "Drift Assumption",
        "question": "What is the 'drift' in a Monte Carlo simulation?",
        "answer": "The expected annual return before volatility is applied — the centre of gravity around which random outcomes scatter",
        "distractors": [
            "The maximum possible loss the simulation will allow",
            "The number of years simulated",
            "The correlation between two specific assets",
        ],
    },
    {
        "term_key": "percentile-fan",
        "section_id": "machine-learning",
        "term_title": "Percentile Fan",
        "question": "What does a wide Percentile Fan indicate?",
        "answer": "Outcomes are highly dispersed — higher volatility and/or a longer time horizon",
        "distractors": [
            "The simulation only ran 100 paths instead of 1,000",
            "The portfolio is guaranteed to underperform its target",
            "All five percentile lines converge to the same value",
        ],
    },
    {
        "term_key": "probability-of-success",
        "section_id": "machine-learning",
        "term_title": "Probability of Success",
        "question": "What does a Probability of Success of 0.73 mean?",
        "answer": "730 out of 1,000 simulated futures reached or exceeded the target wealth level",
        "distractors": [
            "The portfolio has a 73% chance of losing money next year",
            "73% of the portfolio is allocated to equities",
            "The simulation ran for exactly 73 years",
        ],
    },

    # --- earnings-vol ---
    {
        "term_key": "what-happens-at-earnings",
        "section_id": "earnings-vol",
        "term_title": "What Happens at Earnings",
        "question": "What determines whether a stock jumps or falls after an earnings announcement?",
        "answer": "Whether the actual reported results beat or missed the consensus analyst estimate",
        "distractors": [
            "Whether the announcement happens before or after market close",
            "The size of the company's total market capitalisation",
            "Whether the CEO personally presents the results",
        ],
    },
    {
        "term_key": "implied-move-atm-straddle",
        "section_id": "earnings-vol",
        "term_title": "Implied Move (ATM Straddle)",
        "question": "What does the cost of an ATM straddle directly tell you?",
        "answer": "The options market's consensus forecast of how big the earnings move will be, in either direction",
        "distractors": [
            "The exact direction the stock will move after earnings",
            "The company's expected revenue growth rate",
            "The dividend that will be paid on the ex-date",
        ],
    },
    {
        "term_key": "historical-average-move",
        "section_id": "earnings-vol",
        "term_title": "Historical Average Move",
        "question": "How is the Historical Average Move calculated?",
        "answer": "The average of the absolute percentage price changes on the day after each of the last four earnings announcements",
        "distractors": [
            "The average implied volatility over the past year",
            "The stock's average daily move on any random trading day",
            "The percentage difference between analyst high and low estimates",
        ],
    },
    {
        "term_key": "mathematical-edge-score",
        "section_id": "earnings-vol",
        "term_title": "Mathematical Edge Score",
        "question": "What does a positive Edge Score (Historical > Implied) suggest?",
        "answer": "The options are cheap relative to history — a theoretical edge for an options buyer",
        "distractors": [
            "The stock is guaranteed to beat earnings estimates",
            "The company has increased its dividend",
            "Options trading has been halted for that ticker",
        ],
    },

    # --- dip-radar ---
    {
        "term_key": "intraday-mean-reversion",
        "section_id": "dip-radar",
        "term_title": "Intraday Mean Reversion",
        "question": "What condition does Dip Radar require before it considers a snap-back likely?",
        "answer": "Measurable signs of selling exhaustion across multiple independent signals simultaneously, not just one",
        "distractors": [
            "A single day where RSI crosses below 50",
            "The stock must be in a long-term downtrend for over a year",
            "The company must have reported negative earnings that quarter",
        ],
    },
    {
        "term_key": "reversal-score",
        "section_id": "dip-radar",
        "term_title": "Reversal Score (0–100)",
        "question": "What is the alert threshold for the Dip Radar Reversal Score?",
        "answer": "A score of 65 or above",
        "distractors": [
            "A score of exactly 100 only",
            "A score of 30 or above",
            "Any score above 0",
        ],
    },
    {
        "term_key": "vwap",
        "section_id": "dip-radar",
        "term_title": "VWAP (Volume Weighted Average Price)",
        "question": "How does VWAP differ from a simple average of intraday prices?",
        "answer": "VWAP weights each price level by how much volume traded there, pulling the value toward heavily-traded price levels",
        "distractors": [
            "VWAP only considers the opening and closing prices of the session",
            "VWAP is recalculated only once per week",
            "VWAP ignores volume entirely and uses time-weighting instead",
        ],
    },
    {
        "term_key": "bollinger-bands-25-sigma",
        "section_id": "dip-radar",
        "term_title": "Bollinger Bands (2.5σ Extreme Variant)",
        "question": "Why does Dip Radar use a wider 2.5σ threshold instead of the standard 2σ?",
        "answer": "To filter out routine volatility and identify only genuinely extreme dislocations",
        "distractors": [
            "Because 1-minute data cannot support a 2σ calculation",
            "To make alerts fire more frequently throughout the session",
            "Because 2.5σ is the regulatory standard for volatility bands",
        ],
    },
    {
        "term_key": "volume-capitulation-climax-volume",
        "section_id": "dip-radar",
        "term_title": "Volume Capitulation (Climax Volume)",
        "question": "What does an extreme volume spike on a down-candle typically indicate?",
        "answer": "Forced sellers (margin calls, stop-losses, panic) have been flushed out simultaneously, often exhausting selling pressure",
        "distractors": [
            "The company has just announced a stock buyback program",
            "Trading has been halted due to a circuit breaker",
            "Institutional buyers are selling to book profits",
        ],
    },
    {
        "term_key": "session-scoped-monitoring",
        "section_id": "dip-radar",
        "term_title": "Session-Scoped Monitoring",
        "question": "Why must Dip Radar be manually activated per ticker rather than scanning continuously?",
        "answer": "Continuous scanning of thousands of tickers would generate enormous, mostly noisy alert volumes",
        "distractors": [
            "The exchange only allows 5-minute scans for pre-approved tickers",
            "It reduces the Yahoo Finance data fetch cost to zero",
            "Manual activation is required by financial regulation",
        ],
    },

    # --- bubble-radar ---
    {
        "term_key": "what-bubble-radar-detects",
        "section_id": "bubble-radar",
        "term_title": "What Bubble Radar Detects",
        "question": "What does a high Bubble Radar score prompt you to consider?",
        "answer": "Whether you're comfortable holding at these valuation levels and whether you have an exit plan — not a prediction of when it will burst",
        "distractors": [
            "An immediate mandatory sell order",
            "That the stock will definitely crash within 24 hours",
            "That the company's accounting is fraudulent",
        ],
    },
    {
        "term_key": "bubble-risk-score",
        "section_id": "bubble-radar",
        "term_title": "Bubble Risk Score",
        "question": "Why is the Bubble Risk Score threshold-based rather than percentile-ranked against the market?",
        "answer": "So a score of 80 means the same absolute level of overextension for both a small-cap and a mega-cap stock",
        "distractors": [
            "Because percentile ranking is computationally too expensive to calculate",
            "Because threshold-based scoring only works for US-listed stocks",
            "Because percentile ranking requires real-time options data",
        ],
    },
    {
        "term_key": "sma-200-extension",
        "section_id": "bubble-radar",
        "term_title": "SMA-200 Extension",
        "question": "Why is the 200-day SMA often treated as a proxy for long-run fair value?",
        "answer": "It moves very slowly and isn't easily distorted by short-term news events",
        "distractors": [
            "It is recalculated every 5 minutes during market hours",
            "It only applies to ETFs, not individual stocks",
            "It always equals the stock's average P/E ratio",
        ],
    },
    {
        "term_key": "sustained-rsi-high",
        "section_id": "bubble-radar",
        "term_title": "Sustained RSI High",
        "question": "What is unusual and historically correlated with bubbles regarding RSI?",
        "answer": "RSI averaging above 70 over 20 consecutive trading days, not just a single overbought day",
        "distractors": [
            "RSI falling below 30 for a single session",
            "RSI staying exactly at 50 for a month",
            "RSI diverging from price on a single day",
        ],
    },
    {
        "term_key": "fcf-yield-vs-real-10-year",
        "section_id": "bubble-radar",
        "term_title": "FCF Yield vs Real 10-Year",
        "question": "What does it mean when a company's FCF yield falls below the real risk-free rate?",
        "answer": "Equity holders are accepting a lower expected return than risk-free government bonds, with far more risk — a textbook bubble indicator",
        "distractors": [
            "The company has zero debt on its balance sheet",
            "The company's dividend has just been increased",
            "The company is guaranteed to be acquired within a year",
        ],
    },
    {
        "term_key": "iv-call-skew",
        "section_id": "bubble-radar",
        "term_title": "IV Call Skew",
        "question": "What does it mean when call option implied volatility exceeds put implied volatility?",
        "answer": "The options market is pricing in more upside uncertainty than downside — historically associated with late-stage speculative excess",
        "distractors": [
            "The stock is guaranteed to fall in the near term",
            "The company has just announced a stock split",
            "Trading in the underlying stock has been suspended",
        ],
    },
    {
        "term_key": "spy-vs-rsp-breadth-spread",
        "section_id": "bubble-radar",
        "term_title": "SPY vs RSP Breadth Spread",
        "question": "What does a large positive spread between SPY and RSP (equal-weight) performance indicate?",
        "answer": "A small number of mega-cap stocks are doing all the heavy lifting while the average stock lags — narrow breadth",
        "distractors": [
            "The overall market is falling broadly across all 500 stocks",
            "RSP has been discontinued and no longer trades",
            "All 500 S&P constituents are rising at an identical rate",
        ],
    },
    {
        "term_key": "bubble-watch-vs-bubble-risk",
        "section_id": "bubble-radar",
        "term_title": "Bubble Watch vs Bubble Risk",
        "question": "What distinguishes 'Bubble Risk' (red flag) from 'Bubble Watch' (yellow flag)?",
        "answer": "Bubble Risk means the composite score has crossed the upper threshold with multiple metrics simultaneously in extreme territory",
        "distractors": [
            "Bubble Risk only applies to non-US stocks",
            "Bubble Watch is a lagging indicator computed after Bubble Risk",
            "Bubble Risk requires manual confirmation from an analyst",
        ],
    },

    # --- forensic-screener ---
    {
        "term_key": "why-forensic-accounting-matters",
        "section_id": "forensic-screener",
        "term_title": "Why Forensic Accounting Matters",
        "question": "What is the core problem the Forensic Screener addresses?",
        "answer": "Some companies exploit the gap between reported numbers and economic reality through aggressive accounting or manipulated accruals",
        "distractors": [
            "Most companies deliberately underreport their true profits",
            "Financial statements are only published once every five years",
            "Price charts already fully capture a company's true financial health",
        ],
    },
    {
        "term_key": "piotroski-f-score",
        "section_id": "forensic-screener",
        "term_title": "Piotroski F-Score",
        "question": "What does a Piotroski F-Score below 4 suggest?",
        "answer": "Structural decay — the company is deteriorating across multiple financial dimensions simultaneously",
        "distractors": [
            "The company is a guaranteed short-selling opportunity",
            "The company has too much cash on its balance sheet",
            "The company qualifies as a Quality Compounder",
        ],
    },
    {
        "term_key": "altman-z-score",
        "section_id": "forensic-screener",
        "term_title": "Altman Z-Score",
        "question": "What does an Altman Z-Score below 1.1 suggest?",
        "answer": "The company's financials look statistically similar to companies that filed for bankruptcy within 2 years",
        "distractors": [
            "The company is definitely going to go bankrupt within 2 years",
            "The company has an unusually high dividend yield",
            "The company's Piotroski F-Score is automatically also low",
        ],
    },
    {
        "term_key": "beneish-m-score",
        "section_id": "forensic-screener",
        "term_title": "Beneish M-Score",
        "question": "What does the Beneish M-Score attempt to detect?",
        "answer": "Statistical signatures of earnings manipulation in reported financial statements",
        "distractors": [
            "The probability of bankruptcy within 2 years",
            "Overall financial health across profitability, leverage, and efficiency",
            "The company's dividend sustainability",
        ],
    },

    # --- fx-drag ---
    {
        "term_key": "currency-problem-uk-investors",
        "section_id": "fx-drag",
        "term_title": "The Currency Problem for UK Investors",
        "question": "What two separate factors determine a UK investor's GBP return on a US stock?",
        "answer": "How the stock performed in USD, and how the GBP/USD exchange rate moved over the same period",
        "distractors": [
            "The stock's dividend yield and its P/E ratio",
            "The size of the position and the broker's commission",
            "The stock's beta and its market capitalisation",
        ],
    },
    {
        "term_key": "fx-drag-term",
        "section_id": "fx-drag",
        "term_title": "FX Drag",
        "question": "When does a UK investor experience negative FX drag (a headwind)?",
        "answer": "When GBP strengthens against USD, making the dollar-denominated asset worth fewer pounds when converted back",
        "distractors": [
            "When GBP weakens against USD",
            "When the stock itself falls in USD terms",
            "When the company pays a dividend in USD",
        ],
    },
    {
        "term_key": "equity-return-usd",
        "section_id": "fx-drag",
        "term_title": "Equity Return (USD)",
        "question": "What does 'Equity Return (USD)' isolate?",
        "answer": "How the company itself performed, independent of what currencies were doing",
        "distractors": [
            "The combined GBP return including currency effects",
            "The dividend yield converted into GBP",
            "The stock's beta relative to the S&P 500",
        ],
    },
    {
        "term_key": "total-gbp-return",
        "section_id": "fx-drag",
        "term_title": "Total GBP Return",
        "question": "Why is Total GBP Return calculated multiplicatively rather than by simple addition?",
        "answer": "Both the equity return and FX effect compound simultaneously, and the combined effect differs slightly from their sum",
        "distractors": [
            "Because GBP returns must always be rounded to the nearest whole percent",
            "Multiplication is required by UK tax reporting rules",
            "Addition would always overstate the return",
        ],
    },
    {
        "term_key": "lifetime-mode",
        "section_id": "fx-drag",
        "term_title": "Lifetime Mode",
        "question": "What exchange rate does Lifetime Mode use for FX Drag calculations?",
        "answer": "The actual exchange rate at which each position was originally purchased, derived from account transaction history",
        "distractors": [
            "The exchange rate on the day the app was installed",
            "A single fixed rate configured in Settings",
            "The average exchange rate over the past 10 years",
        ],
    },

    # --- performance-analytics ---
    {
        "term_key": "what-portfolio-tearsheet-does",
        "section_id": "performance-analytics",
        "term_title": "What the Portfolio Tearsheet Does",
        "question": "How does the Portfolio Tearsheet relate to the X-ray panel's risk metrics?",
        "answer": "It deliberately covers metrics X-ray doesn't show (Sortino, Omega, drawdown duration) rather than duplicating Sharpe/VaR/CVaR",
        "distractors": [
            "It replaces X-ray entirely with a more advanced version",
            "It requires a separate external quantstats installation to function",
            "It only works for portfolios with fewer than 5 holdings",
        ],
    },
    {
        "term_key": "sortino-calmar-omega-profit-factor",
        "section_id": "performance-analytics",
        "term_title": "Sortino, Calmar, Omega & Profit Factor",
        "question": "How does the Sortino Ratio differ from the Sharpe Ratio?",
        "answer": "Sortino only penalises downside volatility, so big up-days don't hurt the score",
        "distractors": [
            "Sortino ignores returns entirely and only measures volatility",
            "Sortino is calculated over a fixed 30-day window only",
            "Sortino requires a minimum portfolio size of £100,000",
        ],
    },
    {
        "term_key": "drawdown-duration-ulcer-index",
        "section_id": "performance-analytics",
        "term_title": "Drawdown Duration & the Ulcer Index",
        "question": "What does the Ulcer Index capture that Max Drawdown alone does not?",
        "answer": "How long the portfolio spent underwater, not just how deep the worst decline was",
        "distractors": [
            "The exact date of the portfolio's next drawdown",
            "The correlation between two specific holdings",
            "The dividend yield of the portfolio's largest holding",
        ],
    },
    {
        "term_key": "tail-ratio-win-loss-stats",
        "section_id": "performance-analytics",
        "term_title": "Tail Ratio & Win/Loss Stats",
        "question": "What does a Tail Ratio above 1 indicate?",
        "answer": "The portfolio's best days have historically outsized its worst days",
        "distractors": [
            "The portfolio has never had a losing day",
            "The portfolio's win rate is above 90%",
            "The portfolio holds only bonds, no equities",
        ],
    },
    {
        "term_key": "the-charts-tearsheet",
        "section_id": "performance-analytics",
        "term_title": "The Charts",
        "question": "What does the Monthly Returns Heatmap in the Portfolio Tearsheet show?",
        "answer": "Every calendar month's compounded return laid out in a year × month grid, useful for spotting seasonal patterns",
        "distractors": [
            "A single number summarising the entire portfolio's lifetime return",
            "The correlation matrix between all portfolio holdings",
            "Only the most recent month's daily returns",
        ],
    },

    # --- stress-tester ---
    {
        "term_key": "what-stress-tester-does",
        "section_id": "stress-tester",
        "term_title": "What the Stress Tester Does",
        "question": "What is the purpose of the Historical Stress Tester?",
        "answer": "To make investors viscerally aware of the downside before it happens, using concrete monetary loss figures",
        "distractors": [
            "To predict the exact date of the next market crash",
            "To automatically sell holdings that fail the stress test",
            "To calculate a portfolio's dividend income under each scenario",
        ],
    },
    {
        "term_key": "beta-adjusted-scenario-shock",
        "section_id": "stress-tester",
        "term_title": "Beta-Adjusted Scenario Shock",
        "question": "How is a holding's estimated drop calculated in the Stress Tester?",
        "answer": "Market Crash % × Beta × Sector Multiplier",
        "distractors": [
            "Market Crash % divided by the holding's dividend yield",
            "A fixed 50% drop applied equally to every holding",
            "The holding's own historical maximum drawdown",
        ],
    },
    {
        "term_key": "sector-multiplier",
        "section_id": "stress-tester",
        "term_title": "Sector Multiplier",
        "question": "What does a Sector Multiplier below 1.0 mean for a scenario?",
        "answer": "That sector held up better than the broad index during that historical crisis",
        "distractors": [
            "The sector is guaranteed to rise during any future crash",
            "The sector has no equity holdings, only bonds",
            "The multiplier only applies to non-US sectors",
        ],
    },
    {
        "term_key": "why-not-historical-replay",
        "section_id": "stress-tester",
        "term_title": "Why Not Historical Replay?",
        "question": "Why can't the Stress Tester simply look up each stock's actual historical return during a past crisis?",
        "answer": "The app only holds 2 years of price history, and many holdings didn't exist or traded differently during those historical crises",
        "distractors": [
            "Historical replay is computationally impossible on modern hardware",
            "Regulators prohibit displaying real historical crash data",
            "Beta and sector data are never available for individual stocks",
        ],
    },

    # --- etf-predictor ---
    {
        "term_key": "etf-price-predictor-what-it-solves",
        "section_id": "etf-predictor",
        "term_title": "ETF Price Predictor — What It Solves",
        "question": "What problem does the ETF Price Predictor solve for LSE-listed ETFs holding US stocks?",
        "answer": "The LSE closes hours before US markets, so the ETF's 'last price' can be stale relative to after-hours moves in its US holdings",
        "distractors": [
            "LSE-listed ETFs cannot legally hold any US constituents",
            "ETFs never update their holdings more than once a year",
            "US markets and the LSE always close at exactly the same time",
        ],
    },
    {
        "term_key": "holdings-engine-primary",
        "section_id": "etf-predictor",
        "term_title": "Holdings Engine (Primary)",
        "question": "How does the Holdings Engine compute a predicted next-day ETF open?",
        "answer": "It weights each constituent's after-hours return by its portfolio weight, applies FX adjustment, then applies that to the last close",
        "distractors": [
            "It always assumes the ETF opens flat regardless of constituent moves",
            "It uses only the single largest constituent's return",
            "It requires at least 15 years of historical ETF data",
        ],
    },
    {
        "term_key": "regression-engine-fallback",
        "section_id": "etf-predictor",
        "term_title": "Regression Engine (Fallback)",
        "question": "When does the Regression Engine take over from the Holdings Engine?",
        "answer": "When fewer than 3 constituents have usable data",
        "distractors": [
            "Every single trading day, regardless of data availability",
            "Only when the ETF has more than 20 constituents",
            "When the ETF's ticker contains a currency suffix",
        ],
    },
    {
        "term_key": "bias-corrected-confidence-weighted-blend",
        "section_id": "etf-predictor",
        "term_title": "Bias-Corrected & Confidence-Weighted Blend Predictions",
        "question": "What does the Confidence-Weighted Blend prediction do?",
        "answer": "Combines the Holdings and Regression engines, weighting each by the inverse of its own trailing mean absolute error",
        "distractors": [
            "Always uses the Holdings Engine's result unchanged",
            "Replaces the standard prediction used for Portfolio Impact P&L",
            "Requires manual selection of which engine to trust each day",
        ],
    },
    {
        "term_key": "constituent-weights",
        "section_id": "etf-predictor",
        "term_title": "Constituent Weights",
        "question": "What happens if configured constituent weights sum to only 75%?",
        "answer": "The system normalises them to 100% by dividing each weight by 0.75",
        "distractors": [
            "The prediction fails and no output is produced",
            "The missing 25% is assumed to be held in cash",
            "The system rejects the configuration until it sums to exactly 100%",
        ],
    },

    # --- sovereign-debt-auction ---
    {
        "term_key": "sovereign-debt-auction-monitor",
        "section_id": "sovereign-debt-auction",
        "term_title": "Sovereign Debt Auction Monitor",
        "question": "Why do weak US Treasury auctions matter for stock investors?",
        "answer": "Weak demand raises the government's borrowing rate, which ripples into higher rates economy-wide and reduces the present value of future corporate profits",
        "distractors": [
            "Weak auctions automatically trigger a stock market circuit breaker",
            "Weak auctions only affect companies headquartered in the United States",
            "Treasury auctions have no connection to equity valuations",
        ],
    },
    {
        "term_key": "us-treasury-auction-how-it-works",
        "section_id": "sovereign-debt-auction",
        "term_title": "US Treasury Auction — How It Works",
        "question": "What is the 'stop-out rate' in a Treasury auction?",
        "answer": "The highest yield accepted — the point at which the auction was fully subscribed",
        "distractors": [
            "The lowest yield rejected by the government",
            "A penalty rate charged to late bidders",
            "The average yield across all maturities auctioned that week",
        ],
    },
    {
        "term_key": "bid-to-cover-ratio",
        "section_id": "sovereign-debt-auction",
        "term_title": "Bid-to-Cover Ratio",
        "question": "What does a bid-to-cover ratio of 2.5 mean?",
        "answer": "Investors submitted bids worth 2.5 times the value of bonds offered",
        "distractors": [
            "The auction was undersubscribed by 2.5 times",
            "The government had to raise its yield by 2.5 basis points",
            "2.5% of bidders were foreign central banks",
        ],
    },
    {
        "term_key": "yield-tail",
        "section_id": "sovereign-debt-auction",
        "term_title": "Yield Tail",
        "question": "What does a large yield tail (e.g. +3 basis points) indicate?",
        "answer": "The government had to accept bids at significantly higher yields than the median, suggesting weaker genuine demand",
        "distractors": [
            "The auction attracted more direct bidders than usual",
            "The bond's face value was increased after the auction",
            "The auction happened later in the day than scheduled",
        ],
    },
    {
        "term_key": "direct-bidders",
        "section_id": "sovereign-debt-auction",
        "term_title": "Direct Bidders (%)",
        "question": "What does a rising direct bidder percentage across successive auctions suggest?",
        "answer": "Domestic institutions are increasingly competing for Treasuries — a positive demand signal",
        "distractors": [
            "Foreign governments are increasing their Treasury holdings",
            "Primary dealers are absorbing more of the auction supply",
            "The auction's yield tail is widening",
        ],
    },
    {
        "term_key": "indirect-bidders",
        "section_id": "sovereign-debt-auction",
        "term_title": "Indirect Bidders (%)",
        "question": "Who are 'indirect bidders' in a Treasury auction?",
        "answer": "Primarily foreign central banks, sovereign wealth funds, and overseas government buyers, bidding through primary dealers",
        "distractors": [
            "Domestic pension funds bidding directly through TreasuryDirect",
            "The 24 primary dealer banks obligated to bid at every auction",
            "Individual retail investors buying through their broker",
        ],
    },
    {
        "term_key": "primary-dealers",
        "section_id": "sovereign-debt-auction",
        "term_title": "Primary Dealers (%)",
        "question": "What does it mean when primary dealer absorption rises above 30-35% of an auction?",
        "answer": "Voluntary demand was weak, and the legally obligated dealers had to step in to fill the gap",
        "distractors": [
            "The auction was oversubscribed by voluntary bidders",
            "Foreign central banks bought the entire auction",
            "The bond's maturity was extended",
        ],
    },
    {
        "term_key": "maturity-label",
        "section_id": "sovereign-debt-auction",
        "term_title": "Maturity Label",
        "question": "Why is weak demand for a 30-year Treasury bond generally more concerning than weak demand for a 3-month bill?",
        "answer": "Long-dated weakness signals structural worries about long-run inflation or fiscal sustainability, not just short-term technical noise",
        "distractors": [
            "30-year bonds are auctioned far more frequently than 3-month bills",
            "3-month bills are never purchased by foreign investors",
            "Weak 30-year demand always means bond prices are rising",
        ],
    },
    {
        "term_key": "rolling-6-auction-baseline",
        "section_id": "sovereign-debt-auction",
        "term_title": "Rolling 6-Auction Baseline",
        "question": "Why does the monitor compare each auction only to the previous 6 auctions of the same maturity?",
        "answer": "It balances recency with statistical stability — long enough to be stable, short enough to reflect current conditions, and specific to that maturity's own demand pattern",
        "distractors": [
            "Because only 6 auctions of data are ever stored in the database",
            "Because the Federal Reserve mandates a 6-auction comparison window",
            "Because all maturities share an identical baseline regardless of type",
        ],
    },

    # --- accounts ---
    {
        "term_key": "built-in-accounts-what-it-solves",
        "section_id": "accounts",
        "term_title": "Built-in Accounts — What It Solves",
        "question": "How do Built-in Accounts relate to Ghostfolio?",
        "answer": "They coexist — the Portfolio page merges both sources, summing a ticker held in both into one row",
        "distractors": [
            "Built-in Accounts completely replace and disable Ghostfolio once enabled",
            "Ghostfolio automatically imports all Built-in Account transactions",
            "Built-in Accounts can only be used if Ghostfolio is not configured",
        ],
    },
    {
        "term_key": "account-type",
        "section_id": "accounts",
        "term_title": "Account Type",
        "question": "Which account types are aggregated into portfolio-wide ticker views?",
        "answer": "Only Trading accounts — House, Pension, and Watchlist are excluded by design",
        "distractors": [
            "All four account types equally",
            "Only Pension and House accounts",
            "Only the Watchlist account",
        ],
    },
    {
        "term_key": "xray-sector-geo-lookthrough",
        "section_id": "accounts",
        "term_title": "X-ray Sector & Geographic Look-Through (ETFs / Funds)",
        "question": "How is a fund's Geographic Exposure approximated in X-ray?",
        "answer": "From the fund's top 10 holdings' known countries, with the resolvable subset's weights rescaled to sum to 100%",
        "distractors": [
            "Directly from Yahoo Finance's official country breakdown for the fund",
            "By assuming all funds are 100% domiciled in their listing country",
            "By evenly splitting the fund's weight across every country in its benchmark index",
        ],
    },
    {
        "term_key": "auto-top-up-trading",
        "section_id": "accounts",
        "term_title": "Auto Top-up (Trading)",
        "question": "Why doesn't Auto Top-up post a cash deposit the instant its scheduled date arrives?",
        "answer": "Bank credit dates drift around weekends and bank holidays, so a date-only schedule can't be trusted to match the real ledger",
        "distractors": [
            "The app cannot process transactions on weekends for any reason",
            "Auto Top-up requires manual approval from a bank administrator",
            "Cash deposits over £500 require a separate confirmation step",
        ],
    },
    {
        "term_key": "account-price-scraper",
        "section_id": "accounts",
        "term_title": "Account Price Scraper (House / Pension)",
        "question": "How are House and Pension account values priced, since they have no market ticker?",
        "answer": "A generic URL + CSS selector scraper pulls a price from a configured web page on a schedule",
        "distractors": [
            "They are priced using the same ML Confidence Score model as equities",
            "Ghostfolio must be configured to provide their price",
            "They are manually re-priced once per year by the operator",
        ],
    },
    {
        "term_key": "pay-in-admin-fee-pension",
        "section_id": "accounts",
        "term_title": "Pay In & Admin Fee (Pension)",
        "question": "What does the Admin Fee action let you enter, depending on what your pension provider shows?",
        "answer": "Either the units remaining after the fee, or the units deducted directly",
        "distractors": [
            "Only a percentage fee rate applied automatically each month",
            "The total historical fees charged since the account was opened",
            "A fixed fee amount set once when the account was created",
        ],
    },
    {
        "term_key": "pension-benchmarks",
        "section_id": "accounts",
        "term_title": "Pension Benchmarks",
        "question": "What does 'rebasing' a benchmark line to the pension's starting value achieve?",
        "answer": "It lets all lines sit on the same value axis, answering 'what would this account be worth if it tracked this index instead'",
        "distractors": [
            "It converts the benchmark into a percentage-return-only chart",
            "It resets the benchmark's data to zero every calendar year",
            "It removes the need for a UK CPI comparison line",
        ],
    },
    {
        "term_key": "uk-treasury-bill-zero-coupon",
        "section_id": "accounts",
        "term_title": "UK Treasury Bill (Zero-Coupon)",
        "question": "Why does each Treasury Bill purchase get its own unique internal ticker?",
        "answer": "So holding several bills at once never blends their discount prices together in the average-cost ledger",
        "distractors": [
            "Because UK regulations require a unique ISIN per purchase",
            "To allow the bill to be sold before maturity like a normal stock",
            "Because Yahoo Finance requires a unique ticker for every instrument",
        ],
    },
    {
        "term_key": "watchlist-account",
        "section_id": "accounts",
        "term_title": "Watchlist Account",
        "question": "What makes the Watchlist account different from Trading, House, and Pension accounts?",
        "answer": "Exactly one always exists automatically, holds no transactions, and can't be created, deleted, or converted",
        "distractors": [
            "It is the only account type that supports Buy and Sell transactions",
            "It requires a separate Ghostfolio subscription to function",
            "It is the only account type included in portfolio-wide aggregation",
        ],
    },
    {
        "term_key": "transaction-types-cash-tracking",
        "section_id": "accounts",
        "term_title": "Transaction Types & Cash Tracking",
        "question": "What does the Transfer transaction type do?",
        "answer": "Moves cash between two of your own built-in accounts, recording a linked debit and credit so both balances stay correct",
        "distractors": [
            "Converts shares from one ticker to another automatically",
            "Records a dividend payment received in a foreign currency",
            "Applies a one-time fee to close an account",
        ],
    },
    {
        "term_key": "holdings-closed-positions-realized-pnl",
        "section_id": "accounts",
        "term_title": "Holdings, Closed Positions & Realized P&L",
        "question": "What method is used to derive holdings from an account's transaction ledger?",
        "answer": "Average-cost — each Buy raises the average cost basis, each Sell realises a gain or loss against it",
        "distractors": [
            "First-in-first-out (FIFO) lot matching",
            "Last-in-first-out (LIFO) lot matching",
            "A fixed cost basis set once at account creation",
        ],
    },
    {
        "term_key": "position-targets-low-high",
        "section_id": "accounts",
        "term_title": "Position Targets — Low/High Set Targets",
        "question": "How often can a Position Target notification fire for the same account, ticker, and direction?",
        "answer": "At most once per calendar day, even if the price crosses back and forth over the target repeatedly",
        "distractors": [
            "Every time the price crosses the target, with no limit",
            "Only once ever, for the lifetime of the position",
            "Once per hour during market hours",
        ],
    },
    {
        "term_key": "account-value-snapshot",
        "section_id": "accounts",
        "term_title": "Account Value Snapshot",
        "question": "What does comparing Total Value against Net Contributions on an account's chart show?",
        "answer": "At a glance, whether the account is ahead of or behind what was actually paid in",
        "distractors": [
            "The account's total dividend income for the year",
            "The exact number of transactions recorded in the ledger",
            "The account's current cash-to-equity ratio only",
        ],
    },
    {
        "term_key": "live-return-tiles-mwrr",
        "section_id": "accounts",
        "term_title": "Live Return Tiles & Money-Weighted Rate of Return",
        "question": "Why are period returns on a Trading account shown as a currency amount rather than a percentage?",
        "answer": "Dividing by a small starting value can blow the percentage up into a meaningless figure, while the currency amount stays sane and bounded",
        "distractors": [
            "Percentages are not supported by the underlying database schema",
            "Currency amounts are easier to convert between GBP and USD",
            "Regulators require currency-amount reporting for all UK accounts",
        ],
    },
    {
        "term_key": "portfolio-gain-vs-fx",
        "section_id": "accounts",
        "term_title": "Portfolio Gain vs. Portfolio Gain with FX",
        "question": "When do Portfolio Gain and Portfolio Gain with FX show identical figures?",
        "answer": "For a BASE_CURRENCY-native holding, since its exchange rate is always 1.0",
        "distractors": [
            "Only when the portfolio contains exclusively foreign-currency holdings",
            "Only immediately after a Cash Reconciliation",
            "Never — the two figures always differ by design",
        ],
    },
    {
        "term_key": "twr-vs-twr-with-fx",
        "section_id": "accounts",
        "term_title": "Time-Weighted Return % vs. Time-Weighted Return with FX %",
        "question": "What makes Time-Weighted Return (TWR) different from a simple gain percentage?",
        "answer": "TWR isn't distorted by the timing and size of deposits and withdrawals — it geometrically links returns between snapshots",
        "distractors": [
            "TWR only applies to accounts with no cash transactions",
            "TWR is always higher than a simple gain percentage",
            "TWR requires the account to be at least one year old",
        ],
    },
    {
        "term_key": "cash-reconciliation",
        "section_id": "accounts",
        "term_title": "Cash Reconciliation",
        "question": "What happens when you use the Reconcile feature to enter your real broker balance?",
        "answer": "If the difference from the computed balance is more than half a penny, the app books a single Cash transaction for exactly that difference",
        "distractors": [
            "The app deletes and re-imports the entire transaction history",
            "The reconciliation only works for USD-denominated accounts",
            "A reconciliation always requires contacting the broker directly",
        ],
    },
    {
        "term_key": "import-from-csv",
        "section_id": "accounts",
        "term_title": "Import from CSV",
        "question": "What happens to a CSV row whose ticker can't be resolved to a known symbol?",
        "answer": "It is skipped outright, and listed individually in the result message and Notifications panel",
        "distractors": [
            "It is imported anyway with a blank ticker field",
            "The entire import file is rejected",
            "It is automatically matched to the closest similarly-named ticker",
        ],
    },
    {
        "term_key": "export-to-csv",
        "section_id": "accounts",
        "term_title": "Export to CSV",
        "question": "Why might re-importing an account's own CSV export fail the importer's column check?",
        "answer": "The export's Fee column stands in for two separate import columns (Stamp Duty and Dividend Withheld Tax) that the ledger doesn't track separately",
        "distractors": [
            "Exported files are encrypted and cannot be re-read by the importer",
            "The export format uses a different date standard than the importer expects",
            "CSV export is only available for Watchlist accounts",
        ],
    },

    # --- backup-recovery ---
    {
        "term_key": "automated-backup",
        "section_id": "backup-recovery",
        "term_title": "Automated Backup",
        "question": "What are the three independently-toggled components of a Backup & Recovery archive?",
        "answer": "Data, Models, and Database",
        "distractors": [
            "Logs, Screenshots, and Cache",
            "Users, Sessions, and API Keys",
            "Templates, Static Assets, and Config",
        ],
    },
    {
        "term_key": "recovery",
        "section_id": "backup-recovery",
        "term_title": "Recovery",
        "question": "What should you do after restoring a backup archive?",
        "answer": "Restart the service so every in-memory cache reloads from the restored files",
        "distractors": [
            "Immediately trigger a new backup of the just-restored data",
            "Nothing further is needed — restores apply instantly with no restart",
            "Manually re-enter every transaction from the restored ledger",
        ],
    },

    # --- security-access ---
    {
        "term_key": "embed-token",
        "section_id": "security-access",
        "term_title": "Embed Token",
        "question": "What access does a leaked Embed Token URL expose?",
        "answer": "Only the read-only embedded view of that specific page — not the API Key's full account access",
        "distractors": [
            "Full administrative access to every API endpoint",
            "The ability to modify account transactions remotely",
            "Access to the server's underlying filesystem",
        ],
    },

    # --- workflow-monitor ---
    {
        "term_key": "workflow-monitor-term",
        "section_id": "workflow-monitor",
        "term_title": "Workflow Monitor",
        "question": "What does 'Manual Account Entry' represent on the Workflow Monitor graph?",
        "answer": "A non-scheduled data source (like hand-entered Built-in Account transactions) that still needs to be shown so downstream jobs' inputs are visible",
        "distractors": [
            "A scheduled job that runs every night at midnight",
            "An error state indicating a failed database connection",
            "A deprecated feature kept only for backward compatibility",
        ],
    },
    {
        "term_key": "traffic-light-status",
        "section_id": "workflow-monitor",
        "term_title": "Traffic-Light Status",
        "question": "What does a Red status mean for a job box on the Workflow Monitor?",
        "answer": "The job failed on its last attempt, or is significantly overdue beyond its normal schedule",
        "distractors": [
            "The job is disabled in Settings",
            "The job is a manual, non-scheduled process",
            "The job ran successfully but slightly ahead of schedule",
        ],
    },
    {
        "term_key": "conflict-detection",
        "section_id": "workflow-monitor",
        "term_title": "Conflict Detection",
        "question": "What is 'backwards ordering' in the Workflow Monitor's conflict detection?",
        "answer": "A job scheduled to run before the upstream job that produces the data it depends on",
        "distractors": [
            "Two jobs scheduled to run at the exact same second",
            "A job that has never been run since installation",
            "A job whose output format has changed since the last release",
        ],
    },
    {
        "term_key": "yahoo-finance-api-usage-detail",
        "section_id": "workflow-monitor",
        "term_title": "Yahoo Finance API Usage Detail",
        "question": "What does an amber circle marker on the Yahoo Finance API Usage chart indicate?",
        "answer": "The yfinance library itself logged an ERROR without the app's own request actually failing, so it doesn't count toward the Errors column",
        "distractors": [
            "A rate-limit (HTTP 429) response was received",
            "The request succeeded with no issues at all",
            "The request was made by a scheduled job rather than manual browsing",
        ],
    },

    # --- notification-routing ---
    {
        "term_key": "notification-settings-term",
        "section_id": "notification-routing",
        "term_title": "Notification Settings",
        "question": "What does the Notification Settings panel let you control independently for each event type?",
        "answer": "Whether it goes to the log file, the in-app bell icon, and/or a Nextcloud Talk message",
        "distractors": [
            "Only whether the event is logged, with no other channel options",
            "The exact wording of every notification message",
            "Which user account receives the notification",
        ],
    },
    {
        "term_key": "channels-notification",
        "section_id": "notification-routing",
        "term_title": "Channels",
        "question": "Which notification channel is described as the 'act now' channel?",
        "answer": "Nextcloud Talk, since messages arrive on your phone immediately",
        "distractors": [
            "The log file, since it's checked most frequently",
            "The in-app notification centre bell icon",
            "Email, since it's the most universally supported channel",
        ],
    },
    {
        "term_key": "job-status-vs-alert-sources",
        "section_id": "notification-routing",
        "term_title": "Job Status vs. Alert Sources",
        "question": "What distinguishes 'alert sources' from 'job status events'?",
        "answer": "Alert sources are market-signal events carrying actionable information, appropriate for real-time push delivery",
        "distractors": [
            "Job status events are always higher priority than alert sources",
            "Alert sources only apply to scheduled jobs that run overnight",
            "Job status events cannot be routed to the in-app notification centre",
        ],
    },
    {
        "term_key": "etf-crash-alert-benchmark-resolution",
        "section_id": "notification-routing",
        "term_title": "ETF Crash-Alert Benchmark Resolution",
        "question": "How does the system pick a benchmark for a crashing ETF's Crash Alert context report?",
        "answer": "It looks at the ETF's top-10 holdings, finds the dominant exchange by weight, and compares against that exchange's headline index",
        "distractors": [
            "It always compares every ETF against the S&P 500 regardless of holdings",
            "It requires the operator to manually assign a benchmark for every ETF",
            "It compares the ETF only against its own 200-day moving average",
        ],
    },

    # --- methodology ---
    {
        "term_key": "quantamental-dual-lens",
        "section_id": "methodology",
        "term_title": "Quantamental \"Dual-Lens\" Architecture",
        "question": "In the Quantamental approach, what role does technical analysis play?",
        "answer": "It decides WHEN to buy, timing entries to coincide with momentum confirmation or a regime signal",
        "distractors": [
            "It decides WHAT to buy, based on balance sheet health",
            "It replaces fundamental analysis entirely",
            "It is used only for tax-loss harvesting decisions",
        ],
    },
    {
        "term_key": "hierarchical-signal-purity",
        "section_id": "methodology",
        "term_title": "Hierarchical Signal Purity",
        "question": "When a 2-candle and a 3-candle pattern both appear on the same candles, which takes priority?",
        "answer": "The 3-candle pattern always overrides the 2-candle pattern",
        "distractors": [
            "The pattern that appeared most recently in the app's history",
            "The 2-candle pattern, since it forms faster",
            "Whichever pattern has the higher associated accuracy score that week",
        ],
    },
    {
        "term_key": "finbert-nlp-sentiment-engine",
        "section_id": "methodology",
        "term_title": "FinBERT NLP Sentiment Engine",
        "question": "Why are UK Gilt and US Treasury yield headlines excluded from FinBERT sentiment scoring?",
        "answer": "Words like 'surging yields' read as positive language but are economically toxic for equities, which would create false positive sentiment scores",
        "distractors": [
            "Yield data changes too infrequently to score meaningfully",
            "FinBERT cannot process any numerical content in headlines",
            "Yield headlines are not published in English",
        ],
    },
    {
        "term_key": "glossary-learning-spaced-repetition",
        "section_id": "methodology",
        "term_title": "Glossary Learning (Spaced Repetition)",
        "question": "What determines whether a Glossary Learning card is shown as multiple-choice or a self-graded flip card?",
        "answer": "Its current Leitner box — box 1-2 uses multiple-choice, box 3 and above switches to flip-card recall",
        "distractors": [
            "Whichever mode the operator manually selects at the start of each session",
            "Cards are always shown as multiple-choice regardless of progress",
            "The mode alternates randomly each time the card is due",
        ],
    },
]
